salesforce_ant_45.0/sample/codepkg/objects/AddOn__c.object
<CustomObject>
    <fields>
        <fullName>Ordered_Items__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Ordered Items</label>
        <referenceTo>Ordered_Items__c</referenceTo>
        <relationshipLabel>AddOns</relationshipLabel>
        <relationshipName>AddOns</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Price__c</fullName>
        <label>Price</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <label>AddOns</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>AddOns</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

salesforce_ant_45.0/sample/codepkg/objects/Order.object
<CustomObject>
    <fields>
        <fullName>App_Discount_Value__c</fullName>
        <label>App Discount Value</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>App_Earning_Value__c</fullName>
        <label>App Earning Value</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Applied_Taxes__c</fullName>
        <label>Applied Taxes</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>9.7%</fullName>
                </value>
                <value>
                    <fullName>8.9%</fullName>
                </value>
                <value>
                    <fullName>11.2%</fullName>
                </value>
                <value>
                    <fullName>10.4%</fullName>
                </value>
                <value>
                    <fullName>5.56%</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Booking_Date_Time__c</fullName>
        <label>Booking Date &amp; Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Booking_Note__c</fullName>
        <description>Extra Note</description>
        <label>Booking Note</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Booking_Status_Message__c</fullName>
        <label>Booking Status Message</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Booking_Type__c</fullName>
        <label>Booking Type</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Cart_Commission_Value__c</fullName>
        <label>Cart Commission Value</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Cart_Discount__c</fullName>
        <label>Cart Discount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Cart_Total__c</fullName>
        <label>Cart Total</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>City__c</fullName>
        <label>City</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Coupon_Code__c</fullName>
        <label>Coupon Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Delivery_Charge__c</fullName>
        <label>Delivery Charge</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Driver_Account_Message__c</fullName>
        <label>Driver Account Message</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Driver_Commission_Message__c</fullName>
        <label>Driver Commission Message</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Driver_Commission_Percentage__c</fullName>
        <label>Driver Commission Percentage</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Driver_Commission_Value__c</fullName>
        <label>Driver Commission Value</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Driver_Commission_to_App_Value__c</fullName>
        <label>Driver Commission to App Value</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Driver_Earning_Value__c</fullName>
        <label>Driver Earning Value</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Driver_Tip__c</fullName>
        <label>Driver Tip</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Driver_Total_Earning__c</fullName>
        <label>Driver Total Earning</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Drop_Address__c</fullName>
        <description>Address Line 1</description>
        <label>Drop Address</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Drop_Area__c</fullName>
        <label>Drop Area</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Drop_City__c</fullName>
        <label>Drop City</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Drop_Country__c</fullName>
        <label>Drop Country</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Drop_Place_Name__c</fullName>
        <label>Drop Place Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Drop_Postal_Code__c</fullName>
        <label>Drop Postal Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Due_Date_Time__c</fullName>
        <label>Due Date &amp; Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Order_Id__c</fullName>
        <label>Order Id</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Order_Type_Message__c</fullName>
        <label>Order Type Message</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>PG_Commission_Name__c</fullName>
        <label>PG Commission Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PG_Earning_Value__c</fullName>
        <label>PG Earning Value</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Paid_By_Wallet__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Paid By Wallet</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Payment_Type__c</fullName>
        <label>Payment Type</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Pickup_Address__c</fullName>
        <description>Address Line 1</description>
        <label>Pickup Address</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Pickup_Area__c</fullName>
        <label>Pickup Area</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Pickup_City__c</fullName>
        <label>Pickup City</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Pickup_Country__c</fullName>
        <label>Pickup Country</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Pickup_Place_Name__c</fullName>
        <label>Pickup Place Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Pickup_Postal_Code__c</fullName>
        <label>Pickup Postal Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Promocode_Discount__c</fullName>
        <description>Discount Key</description>
        <label>Promocode Discount</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Store_App_Commission__c</fullName>
        <label>Store App Commission</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Store_Commission_Message__c</fullName>
        <label>Store Commission Message</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Store_Commission_Percentage__c</fullName>
        <label>Store Commission Percentage</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Store_Commission_Type__c</fullName>
        <label>Store Commission Type</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Store_Commission_Value__c</fullName>
        <label>Store Commission Value</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Store_Commission_to_App_Value__c</fullName>
        <label>Store Commission to App Value</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Store_Delivery_Fee__c</fullName>
        <label>Store Delivery Fee</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Store_Discount_Value__c</fullName>
        <label>Store Discount Value</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Store_Dispatcher__c</fullName>
        <description>Nothing to do pending for the order.</description>
        <label>Store Dispatcher</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Store_Driver_Type__c</fullName>
        <label>Store Driver Type</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Store_Earning_Value__c</fullName>
        <label>Store Earning Value</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Store_Free_Delivery__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Store Free Delivery</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Store_Id__c</fullName>
        <description>Unique Mongo Id</description>
        <label>Store Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sub_Total_Without_Tax__c</fullName>
        <label>Sub Total Without Tax</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Sub_Total__c</fullName>
        <label>Sub Total</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Tax_Amount__c</fullName>
        <label>Tax Amount</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Taxes__c</fullName>
        <label>Taxes</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Total_Amount__c</fullName>
        <label>Total Amount</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
</CustomObject>

salesforce_ant_45.0/sample/codepkg/objects/Ordered_Items__c.object
<CustomObject>
    <fields>
        <fullName>Actual_Price__c</fullName>
        <label>Actual Price</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>AddOn_Price__c</fullName>
        <label>AddOn Price</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Item_Discount__c</fullName>
        <label>Item Discount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Item_Image__c</fullName>
        <label>Item Image</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Offer_Id__c</fullName>
        <label>Offer Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Offered_Price__c</fullName>
        <description>Key  ---&gt;  Unit Price</description>
        <label>Offered Price</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Orders__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Order</label>
        <referenceTo>Order</referenceTo>
        <relationshipLabel>Ordered Itmes</relationshipLabel>
        <relationshipName>Ordered_Itmes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Taxes__c</fullName>
        <label>Taxes</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>9.5</fullName>
                </value>
                <value>
                    <fullName>10.5</fullName>
                </value>
                <value>
                    <fullName>7.9</fullName>
                </value>
                <value>
                    <fullName>8.9</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Unit_Id__c</fullName>
        <label>Unit Id</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Unit_Name__c</fullName>
        <label>Unit Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Ordered Items</label>
    <nameField>
        <label>Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Ordered Itmes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

salesforce_ant_45.0/sample/codepkg/classes/OrderAPI2.cls
//<=========================================================> Using PUT METHOD Update Case API <==================================================================>
@RestResource(urlMapping='/Ord/*')
global with sharing class OrderAPI2{
   public Static RestRequest request = RestContext.request;
   public Static RestResponse response = RestContext.response;
   public Static FromJSON jsonBody;
   public Static FromJSON jsonBody1;
     
    @HttpPut
    global static String updateOrderInfo(){
      request.addHeader('Content-Type','application/json');
      Account a;     
      Contact c;
      Order ord;
      List<OrderedItem> s = new List<OrderedItem>();
      List<AddOns> s1 = new List<AddOns>();
      List<Ordered_Items__c>orderedItems = new List<Ordered_Items__c>();
      List<AddOn__c> addOn = new List<AddOn__c>();
      Map<String,List<AddOn__c>> mapAddOns = new Map<String,List<AddOn__c>>();
      Map<String,Ordered_Items__c> checkUnitId =new Map<String,Ordered_Items__c>();
      List<Order>orderList = new List<Order>();
        
        try{
            jsonBody  = (FromJSON)JSON.deserialize(request.requestBody.toString(),FromJSON.class);
            orderList = new List<Order>();
             if(jsonBody != NULL){
                 orderList = [Select Order_Id__c, Status From Order Where Order_Id__c =:jsonBody.orderId ];
            
                 if(orderList.isEmpty()){
                    System.debug('The json is '+ jsonBody);
                    a = [Select id,Unique_Mongo_Id__c,name from Account where Unique_Mongo_Id__c =: jsonBody.storeId];
                    c = [Select id , Mongo_Reference_Id__c From Contact Where Mongo_Reference_Id__c  =: jsonBody.customerId];
                    Date dt = Date.Parse(jsonBody.effectiveDate);
                    ord = new Order();
                    System.debug('the order id is '+ jsonBody.orderId);
                    ord.Order_Id__c = jsonBody.orderId;
                    ord.Store_Id__c = jsonBody.storeId;
                    ord.AccountId = a.id;
                    ord.CustomerAuthorizedById = c.Id;
                    ord.EffectiveDate = dt;
                    ord.Status = checkNull(jsonBody.status);
                    ord.Cart_Total__c = checkIntValue(jsonBody.cartTotal); 
                    ord.Cart_Discount__c = checkIntValue(jsonBody.cartDiscount);
                    ord.Store_App_Commission__c = checkIntValue(jsonBody.storeAppCommission);
                    ord.Store_Commission_Type__c = checkNull(jsonBody.storeCommissionType);
                    ord.Store_Driver_Type__c = checkNull(jsonBody.storeDriverType);
                    ord.Sub_Total__c = checkIntValue(jsonBody.subTotal);
                    ord.Delivery_Charge__c = checkIntValue(jsonBody.deliveryCharge);
                    ord.Store_Free_Delivery__c = jsonBody.storeFreeDelivery;    //<---------Boolean Type
                    ord.Sub_Total_Without_Tax__c = checkIntValue(jsonBody.subTotalWithOutTax);
                    ord.Tax_Amount__c = checkIntValue(jsonBody.taxAmount);
                    ord.Applied_Taxes__c = checkNull(jsonBody.appliedTax);
                    ord.Order_Type_Message__c = checkNull(jsonBody.orderTypeMessage);
                    ord.Promocode_Discount__c = checkIntValue(jsonBody.promoCodeDiscount);
                    ord.Total_Amount__c = checkIntValue(jsonBody.totalAmount);
                    ord.Coupon_Code__c = checkNull(jsonBody.couponCode);
                    ord.Payment_Type__c = checkNull(jsonBody.paymentType);
                    ord.Paid_By_Wallet__c = jsonBody.paidByWallet;          //<-------Boolean Type
                    ord.Booking_Date_Time__c = DateTime.valueOf(jsonBody.bookingDateNTime); //<=======Date and Time Type
                    ord.Due_Date_Time__c = DateTime.valueOf(jsonBody.dueDateNTime);    //<=======Date and Time Value
                    ord.City__c = checkNull(jsonBody.city);
                    ord.Booking_Status_Message__c = checkNull(jsonBody.bookingStatusMessage);
                    ord.Booking_Type__c = checkNull(jsonBody.bookingType);
                    ord.Booking_Note__c = checkNull(jsonBody.bookingNote);
                    ord.Store_Dispatcher__c= checkNull(jsonBody.storeDispatcher);
                    ord.Pickup_Place_Name__c = checkNull(jsonBody.pickUpPlaceName);
                    ord.Pickup_Address__c = checkNull(jsonBody.pickUpAddress);
                    ord.Pickup_City__c = checkNull(jsonBody.pickUpCity);
                    ord.Pickup_Area__c = checkNull(jsonBody.pickUpArea);
                    ord.Pickup_Postal_Code__c = checkNull(jsonBody.pickUpPostalCode);
                    ord.Pickup_Country__c = checkNull(jsonBody.pickUpCountry);
                    ord.Drop_Place_Name__c = checkNull(jsonBody.dropPlaceName);
                    ord.Drop_Address__c = checkNull(jsonBody.dropAddress);
                    ord.Drop_City__c = checkNull(jsonBody.dropCity);
                    ord.Drop_Area__c = checkNull(jsonBody.dropArea);
                    ord.Drop_Postal_Code__c = checkNull(jsonBody.dropPostalCode);
                    ord.Drop_Country__c = checkNull(jsonBody.dropCountry);
                    ord.Driver_Account_Message__c = checkNull(jsonBody.driverAccountMessage);
                    ord.Taxes__c = checkIntValue(jsonBody.taxes);
                    ord.Store_Commission_Percentage__c = checkIntValue(jsonBody.storeCommissionPercentage);
                    ord.Store_Commission_Message__c = checkNull(jsonBody.storeCommissionMessage);
                    ord.Driver_Commission_Percentage__c = checkIntValue(jsonBody.driverCommissionPercentage);
                    ord.Driver_Commission_Message__c = checkNull(jsonBody.driverCommissionMessage);
                    ord.App_Earning_Value__c = checkIntValue(jsonBody.appEarningValue);
                    ord.Driver_Earning_Value__c = checkIntValue(jsonBody.driverEarningValue);
                    ord.Driver_Commission_to_App_Value__c = checkIntValue(jsonBody.driverCommissionToAppValue);
                    ord.Store_Earning_Value__c = checkIntValue(jsonBody.storeEarningValue);
                    ord.Store_Commission_to_App_Value__c = checkIntValue(jsonBody.storeCommissionToAppValue);
                    ord.PG_Commission_Name__c = checkNull(jsonBody.pgCommissionName);
                    ord.Driver_Tip__c = checkIntValue(jsonBody.driverTip);
                    ord.Driver_Total_Earning__c = checkIntValue(jsonBody.driverTotalEarning);
                    ord.Store_Commission_Value__c = checkIntValue(jsonBody.storeCommissionValue);
                    ord.Cart_Commission_Value__c = checkIntValue(jsonBody.cartCommissionValue);
                    ord.Driver_Commission_Value__c = checkIntValue(jsonBody.DriverCommissionValue);
                    ord.App_Discount_Value__c = checkIntValue(jsonBody.appDiscountValue);
                    ord.Store_Discount_Value__c = checkIntValue(jsonBody.storeDiscountValue);
                    ord.Store_Delivery_Fee__c = checkIntValue(jsonBody.storeDeliveryFee);
                    ord.PG_Earning_Value__c = checkIntValue(jsonBody.pgEarningValue);
                    orderList.add(ord);
                 }
                                  
                if(!orderList.isEmpty()){
                    if(jsonBody.status!= NULL ){ 
                        orderList[0].Status = jsonBody.status;
                               
                    }
                }
           
            upsert orderList;
            
            //<============================================== For Ordered Items & AddONs ========================================================>
             s =(List<OrderedItem>)jsonBody.orderItems;
                System.debug('The Main Json is'+ jsonBody);
                System.debug('The ordered Items is '+ s.get(0));
                if(s != NULL){
                    for(Integer i=0;i<s.size();i++){ 
                        Ordered_Items__c ordItems = new Ordered_Items__c(); 
                        ordItems.Orders__c = ord.id;
                        ordItems.Unit_Id__c = s.get(i).unitId;
                        ordItems.Name = s.get(i).itemName;
                        ordItems.Unit_Name__c = checkNull(s.get(i).unitName);
                        ordItems.Actual_Price__c = checkIntValue(s.get(i).actualPrice);
                        ordItems.Offered_Price__c = checkIntValue(s.get(i).offeredPrice);
                        ordItems.Item_Discount__c = checkIntValue(s.get(i).itemDiscount);
                        ordItems.Item_Image__c = checkNull(s.get(i).itemImage);
                        ordItems.Offer_Id__c = checkNull(s.get(i).offerId);
                        ordItems.Taxes__c = checkNull(s.get(i).taxes);
                        ordItems.AddOn_Price__c = checkIntValue(s.get(i).addOnPrice);
                         
                        s1 = s.get(i).addOns;
                        if(s1 != NULL){
                        List<AddOn__c> listAddon =new List<AddOn__c>();
                        for(AddOns str :s1){
                            AddOn__c ad = new AddOn__c(); 
                            ad.Name = checkNull(str.name);
                            ad.Price__c = checkIntValue(str.price);
                            listAddon.add(ad);  
                         }
                            mapAddOns.put(ordItems.Unit_Id__c,listAddOn);
                        }
                        orderedItems.add(ordItems);
                    }
                }
                System.debug('The orderedItems List size is '+orderedItems.size());
                if(!orderedItems.isEmpty()){
                    insert orderedItems;    
                }
                
                for(Ordered_Items__c orderI :orderedItems){
                    checkUnitId.put(orderI.Unit_Id__c,orderI);
                }
                
                 for(String st :mapAddOns.keySet()){
                    for(AddOn__c adon :mapAddOns.get(st)){
                        if(checkUnitId.containskey(st)){
                            Ordered_Items__c orderItems = checkUnitId.get(st);
                            adon.Ordered_Items__c =orderItems.id;
                            addOn.add(adon);
                        }
                    }
                }
                
                System.debug('The AddOn List size is '+addOn.size());
                if(!addOn.isEmpty()){
                    insert addOn;
                }              
            } 
        }

        catch(Exception e) {   
            System.debug('The following error has occurred :' + e.getMessage());  
        } 
        return 'Order Info has been Updated OR Inserted Succesfully and OrderId is '+jsonBody.orderId;  
    }    
                
    public class FromJSON {
        public String orderId;
        public String storeId;
        public String customerId;
        public Double cartTotal;
        public Double cartDiscount; 
        public String effectiveDate;
        public String status;
        public Double storeAppCommission;
        public String storeCommissionType;
        public String storeDriverType;
        public Double subTotal;
        public Double deliveryCharge;
        public Boolean storeFreeDelivery;
        public Double subTotalWithOutTax;
        public Double taxAmount;
        public String appliedTax;
        public String orderTypeMessage;
        public Double promoCodeDiscount;
        public Double totalAmount;
        public String couponCode;
        public String paymentType;
        public Boolean paidByWallet;
        public String bookingDateNTime;
        public String dueDateNTime;
        public String city;
        public String bookingStatusMessage;
        public String bookingType;
        public String bookingNote;
        public String storeDispatcher;
        public String pickUpPlaceName;
        public String pickUpAddress;
        public String pickUpCity;
        public String pickUpArea;
        public String pickUpPostalCode;
        public String pickUpCountry;
        public String dropPlaceName;
        public String dropAddress;
        public String dropCity;
        public String dropArea;
        public String dropPostalCode;
        public String dropCountry; 
        public String driverAccountMessage;
        public Double taxes;
        public Double storeCommissionPercentage;
        public String storeCommissionMessage;
        public Double driverCommissionPercentage;
        public String driverCommissionMessage;
        public Double appEarningValue;
        public Double driverEarningValue;
        public Double driverCommissionToAppValue;
        public Double storeEarningValue;
        public Double storeCommissionToAppValue;
        public String pgCommissionName;
        public Double driverTip;
        public Double driverTotalEarning;
        public Double storeCommissionValue;
        public Double cartCommissionValue;
        public Double driverCommissionValue;
        public Double appDiscountValue;
        public Double storeDiscountValue;
        public Double storeDeliveryFee;
        public Double pgEarningValue; 
        public List<OrderedItem> orderItems;
            
     }
     
    public class OrderedItem{
        public String unitId;
        public String itemName;
        public String unitName;
        public Double actualPrice;
        public Double offeredPrice;
        public Double itemDiscount;
        public String itemImage;
        public String offerId;
        public String taxes;
        public Double addOnPrice;
        public List<AddOns> addOns;
        
     }
    public class AddOns{
        public String name;
        public Double price;
        
     }
      
    public Static String checkNull(String str){
        if(!String.isBlank(str)){
            return str;
        }
        return '';
    }
    public static Double checkIntValue(Double intValue ){
        if(String.isBlank(String.valueOf(intValue)) || intValue == Null){  
            return 0.0;
        }
        return intValue;      
    }                 
}