salesforce_ant_45.0/sample/codepkg/objects/AddOn__c.object
<CustomObject>
    <fields>
        <fullName>AddOn_Id__c</fullName>
        <label>AddOn Id</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Ordered_Items__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Ordered Items</label>
        <referenceTo>Ordered_Items__c</referenceTo>
        <relationshipLabel>AddOns</relationshipLabel>
        <relationshipName>AddOns</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Price__c</fullName>
        <label>Price</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <label>AddOns</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>AddOns</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

salesforce_ant_45.0/sample/codepkg/objects/Order.object
<CustomObject>
    <fields>
        <fullName>Taxes__c</fullName>
        <label>Taxes</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
</CustomObject>

salesforce_ant_45.0/sample/codepkg/objects/Ordered_Item_AddOn__c.object
<CustomObject>
    <fields>
        <fullName>AddOns__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>AddOns</label>
        <referenceTo>AddOn__c</referenceTo>
        <relationshipLabel>Ordered Item &amp; AddOns</relationshipLabel>
        <relationshipName>Ordered_Item_AddOns</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Ordered_Items__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Ordered Items</label>
        <referenceTo>Ordered_Items__c</referenceTo>
        <relationshipLabel>Ordered Item &amp; AddOns</relationshipLabel>
        <relationshipName>Ordered_Item_AddOns</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Ordered Item &amp; AddOn</label>
    <nameField>
        <displayFormat>OA-{0000}</displayFormat>
        <label>Ordered Item &amp; AddOn</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Ordered Item &amp; AddOns</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

salesforce_ant_45.0/sample/codepkg/objects/Ordered_Items__c.object
<CustomObject>
    <fields>
        <fullName>Actual_Price__c</fullName>
        <label>Actual Price</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>AddOn_Price__c</fullName>
        <label>AddOn Price</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Item_Discount__c</fullName>
        <label>Item Discount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Item_Image__c</fullName>
        <label>Item Image</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Offer_Id__c</fullName>
        <label>Offer Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Offered_Price__c</fullName>
        <description>Key  ---&gt;  Unit Price</description>
        <label>Offered Price</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Orders__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Order</label>
        <referenceTo>Order</referenceTo>
        <relationshipLabel>Ordered Itmes</relationshipLabel>
        <relationshipName>Ordered_Itmes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Taxes__c</fullName>
        <label>Taxes</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>9.5</fullName>
                </value>
                <value>
                    <fullName>10.5</fullName>
                </value>
                <value>
                    <fullName>7.9</fullName>
                </value>
                <value>
                    <fullName>8.9</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Unit_Id__c</fullName>
        <label>Unit Id</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Unit_Name__c</fullName>
        <label>Unit Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Ordered Items</label>
    <nameField>
        <label>Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Ordered Itmes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

salesforce_ant_45.0/sample/codepkg/classes/OrderItemsListController.cls
public class OrderItemsListController {
    public Set<Id> addOnId;
    public List<Ordered_Items__c> orderedItemList{get;set;}
    public List<AddOn__c> addOnList{get;set;}
    public List<Ordered_Item_AddOn__c> orderItemAddOn;
    
    public OrderItemsListController(ApexPages.StandardController controller) {
        addOnId = new Set<Id>();
        orderedItemList = new List<Ordered_Items__c>();
        addOnList = new List<AddOn__c>();
        orderItemAddOn = new List<Ordered_Item_AddOn__c>();
        
        orderedItemList = [SELECT Name,Unit_Id__c,Unit_Name__c,Orders__c,Taxes__c,Offer_Id__c,Offered_Price__c,Item_Image__c,Item_Discount__c,AddOn_Price__c,Actual_Price__c FROM Ordered_Items__c 
                           WHERE Orders__c =: ApexPages.currentPage().getParameters().get('id') ORDER BY Unit_Id__c];
        
        orderItemAddOn = [Select id , AddOns__c , Ordered_Items__c From Ordered_Item_AddOn__c where Ordered_Items__c IN: orderedItemList];
        
        for(Ordered_Item_AddOn__c ordItemAddOn : orderItemAddOn){
            addOnId.add(ordItemAddOn.AddOns__c);   
        }
        
        addOnList = [SELECT Id , AddOn_Id__c , Name , Price__c FROM Addon__c WHERE id IN: addOnId ORDER BY AddOn_Id__c  ];
       
    }
  
}