salesforce_ant_45.0/sample/codepkg/objects/Order.object
<CustomObject>
    <fields>
        <fullName>Pickup_Area__c</fullName>
        <label>Pickup Area</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Total_Amount__c</fullName>
        <label>Total Amount</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
</CustomObject>

salesforce_ant_45.0/sample/codepkg/classes/OrderListController.cls
public class OrderListController {
    public List<Order> orderList{get;set;}

    public OrderListController(ApexPages.StandardController controller) {
        orderList = new List<Order>();
        orderList = [Select id,Name,OrderNumber,EffectiveDate,AccountID,CustomerAuthorizedByID,Total_Amount__c,Pickup_Area__c From Order where CustomerAuthorizedByID =: 
                     ApexPages.currentPage().getParameters().get('id') ORDER BY OrderNumber];

    }

}