salesforce_ant_45.0/sample/codepkg/objects/Wallet_Transactions__c.object
<CustomObject>
    <fields>
        <fullName>Amount__c</fullName>
        <label>Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Cash_Collected__c</fullName>
        <label>Cash Collected</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>City_Id__c</fullName>
        <label>City Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>City_Name__c</fullName>
        <label>City Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Closing_Balance__c</fullName>
        <label>Closing Balance</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Comment__c</fullName>
        <label>Comment</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Currency__c</fullName>
        <label>Currency</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Customer_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Customer Name</label>
        <referenceTo>Contact</referenceTo>
        <relationshipName>Wallet_Transactions_For_Customers</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Mongo_Id__c</fullName>
        <label>Mongo Id</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Opening_Balance__c</fullName>
        <label>Opening Balance</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Order_Id__c</fullName>
        <label>Order Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Payment_Type__c</fullName>
        <label>Payment Type</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Store_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Store Name</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Wallet_Transactions_For_Customers</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Transaction_Date__c</fullName>
        <label>Transaction Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Transaction_Type__c</fullName>
        <label>Transaction Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>CREDIT</fullName>
                </value>
                <value>
                    <fullName>DEBIT</fullName>
                </value>
                <value>
                    <fullName>PAYMENT</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Wallet Transactions</label>
    <nameField>
        <label>Transaction Id</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Wallet Transactions</pluralLabel>
    <recordTypes>
        <fullName>Store</fullName>
        <active>true</active>
        <description>Wallet Transactions for Store&apos;s.</description>
        <label>Store</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

salesforce_ant_45.0/sample/codepkg/classes/CustomerWalletTxn.cls
@RestResource(urlMapping='/WalletTxnContact/*')
global with sharing class CustomerWalletTxn {
    public static RestRequest request = RestContext.request;
    public static RestResponse response = RestContext.response;  
    public static CustomerJSON jsonBody; 
    public static Wallet_Transactions__c walletTxn; 

    @HttpPost
    global static String returnCustomerWalletInfo() {
        response.addHeader('Content-Type','application/json');
        List<Contact> con= new List<contact>();
        Account acc;
        Date dt;
       
        try {
             jsonBody  = (CustomerJSON) JSON.deserialize(request.requestBody.toString(),CustomerJSON.class);
             dt = Date.parse(jsonBody.txnDate);
             System.debug('The json is '+jsonBody);
             
           /*  if(jsonBody.storeMongoId != Null && jsonBody.customerMongoId ==Null){
                 acc =[select id,Unique_Mongo_Id__c,Name from Account where Unique_Mongo_Id__c=:jsonBody.storeMongoId];
                 walletTxn = new Wallet_Transactions__c();
                 walletTxn.name = checkNull(jsonBody.txnId);
                 //System.debug('The Name is' +jsonBody.txnId);
                 walletTxn.Amount__c=jsonBody.amount;
                 walletTxn.Cash_Collected__c= jsonBody.cashCollected;
                 //customerWalletTxn.City_Id__c = checkNull(jsonBody.cityId);
                 WalletTxn.City_Name__c = checkNull(jsonBody.cityName);
                 //customerWalletTxn.Comment__c = checkNull(jsonBody.comment);
                 walletTxn.Currency__c = checkNull(jsonBody.currencyType);
                 walletTxn.Store_Name__c = acc.Id;
                 walletTxn.Closing_Balance__c = jsonBody.closingBalance;    
                 walletTxn.Transaction_Date_and_Time__c=DateTime.parse(jsonBody.txnDateAndTime);
                 walletTxn.Opening_Balance__c= jsonBody.openingBalance;
                 walletTxn.Order_Id__c= jsonBody.orderId;
                 walletTxn.Payment_Type_Text__c = checkNull(jsonBody.paymentType);
                 //customerWalletTxn.Mongo_Id__c = jsonBody.mongoId;
                 walletTxn.Transaction_Type__c = checkNull(jsonBody.txnType);
             } */
             
              if(jsonBody != Null ) {
                 con =[select id,Mongo_Reference_Id__c,Name from Contact where Mongo_Reference_Id__c=:jsonBody.userMongoId];
                 System.debug('The con size is' + con.size());
                 walletTxn = new Wallet_Transactions__c();
                 walletTxn.name = checkNull(jsonBody.txnId);
                 
                 walletTxn.Amount__c=jsonBody.amount;
                 walletTxn.Cash_Collected__c= jsonBody.cashCollected;
                 //customerWalletTxn.City_Id__c = checkNull(jsonBody.cityId);
                 WalletTxn.City_Name__c = checkNull(jsonBody.cityName);
                 //customerWalletTxn.Comment__c = checkNull(jsonBody.comment);
                 walletTxn.Currency__c = checkNull(jsonBody.currencyType);
                 walletTxn.Customer_Name__c = con[0].Id;
                 walletTxn.Closing_Balance__c = jsonBody.closingBalance;    
                 walletTxn.Transaction_Date__c = dt;
                 walletTxn.Opening_Balance__c= jsonBody.openingBalance;
                 walletTxn.Order_Id__c= jsonBody.orderId;
                 walletTxn.Payment_Type__c = checkNull(jsonBody.paymentType);
                 //customerWalletTxn.Mongo_Id__c = jsonBody.mongoId;
                 walletTxn.Transaction_Type__c = checkNull(jsonBody.txnType);
             }  
             
             
             System.debug('The Json Is '+walletTxn);
             
          /*   Database.DMLOptions dml = new Database.DMLOptions(); 
             dml.DuplicateRuleHeader.allowSave = true;
             dml.DuplicateRuleHeader.runAsCurrentUser = true;
             //Account duplicateAccount = new Account(Name='dupe');
             Database.SaveResult sr = Database.insert(walletTxn, dml);   */ 
        }
        Catch(Exception e){
                System.debug('The following error has occurred :' + e.getMessage());
        }
        System.debug('The Json Is'+ walletTxn);
        insert walletTxn;
        if(walletTxn.id != NULL ){
            System.debug('The New store is created and name is '+ walletTxn.Name);
            return 'returnClientInfo finished.' + jsonBody.userMongoId+ ' ' + jsonBody.paymentType+ ' '+ jsonBody.txnId + 'request=' + request ;
        }
        return 'INVALID ID';
    } 
      
    public class CustomerJSON {
        //public String mongoId;
        public Double amount;
        public Double cashCollected;
        public String cityId; 
        public String cityName;
        public String comment;
        public String currencyType;
        public Double openingBalance;
        public String orderId;
        public String txnId;  
        public String txnType;
        public String serviceType;
        public Boolean test;
        public Double closingBalance;
        public String txnDate;
        public String triggerType;  
        public String paymentType;
        public String userMongoId;
        //public String storeMongoId;
        
     } 
     
    public Static String checkNull(String str){
        if(!String.isBlank(str)){
         return str;
        }return '';
    }   
    
   
}